import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="m-auto mt-20 border-grey-300 border w-96 p-10 m-10 border-grey-700 cursor-pointer">
        <h1 className="text-black-400 text-center hover:(text-red-800 text-2xl )">
          Go to product
        </h1>
      </div>
    </>
  );
}
